steps:
  # 1. Build the Docker container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=https://rdsaohuyogbgodyfkyex.supabase.co'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkc2FvaHV5b2diZ29keWZreWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIwMzc1MzgsImV4cCI6MjA5NzYxMzUzOH0.z7pfbWPznnnuv_sYU8Dc6ougulrslIGfQv-EhqYXYGY'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://callagent-backend-374294783677.asia-south1.run.app/api/v1'
      - '--build-arg'
      - 'NEXT_PUBLIC_TENET_API_KEY=your_dashboard_key'
      - '-t'
      - 'asia-south1-docker.pkg.dev/ai-calling-agent-piyushchokker/callagent-repo/callagent-frontend:$COMMIT_SHA'
      - '.'
    
  # 2. Push the container image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'asia-south1-docker.pkg.dev/ai-calling-agent-piyushchokker/callagent-repo/callagent-frontend:$COMMIT_SHA'
    
  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'callagent-frontend'
      - '--image'
      - 'asia-south1-docker.pkg.dev/ai-calling-agent-piyushchokker/callagent-repo/callagent-frontend:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated'

# Specify the images to be pushed
images:
  - 'asia-south1-docker.pkg.dev/ai-calling-agent-piyushchokker/callagent-repo/callagent-frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
